name: Deploy static site to AWS

on:
  push:
    branches: ["main"]

permissions:
  id-token: write   # нужно для OIDC
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Debug bucket
        run: echo "Deploying to ${{ vars.S3 }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync site to S3
        run: aws s3 sync site/ "s3://${{ vars.S3 }}/" --delete --exclude ".DS_Store"

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT }} --paths "/*"
